services:

  # prom_init:
  #   image: prom/prometheus:v3.2.1
  #   user: root
  #   entrypoint:
  #     - /bin/sh
  #     - -c
  #     - |
  #       chown -R 65534:65534 /prometheus
  #   volumes:
  #     - /data/prometheus:/prometheus
      

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.2.1
    volumes:
      - ./prometheus/prometheus.yml/:/etc/prometheus/prometheus.yml
      - prom:/prometheus

    ports:
      - 9090:9090
    restart: unless-stopped
    # depends_on:
    #   - prom_init

  grafana: 
    container_name: grafana
    image: grafana/grafana:11.5.2
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=1234
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana:/var/lib/grafana

volumes:
  grafana:
  prom:


