global:
  scrape_interval: 15s 
  evaluation_interval: 15s 


scrape_configs:
  - job_name: "prometheus"


    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"

  - job_name: "go_server"
    static_configs:
      - targets: ["172.17.0.1:9999"]


  